### PR TITLE
Add project coordinator

### PR DESCRIPTION
**Pull request by ct-martin**

### CODE REVIEW

**Comment by ct-martin** [comment]
Pending club office approval & club vote

**Review by justwheel — APPROVED** [review]
Simple enough. As @ct-martin mentioned in person, this copytext is sourced directly from the Runbook. This can be the beginning of v1.1 of the constitution.

**Review by axk4545 — APPROVED** [review]
Not sure why we are doing this since we were going to merge runbook and constitution but ok...

**Comment by ct-martin** [comment]
@axk4545 that means that the constitution will be hosted on the runbook, not that the runbook is the constitution. We still have to officially update the constitution with all the formal-ish procedures, inc. going to club office.

**Review by Serubin — APPROVED** [review]

**Pull request merged**
